module imm_gen (
  input logic [31:0] instr, // Instruction bit encoding
  input logic  [2:0] sel, // input from control unit saying what type of instruction I , S, B, U, J
  output logic [31:0] imm // 32-bit immediate generated by the module
);
 
  always_comb begin
    imm = 'd0;
    case (sel)
      3'd0: imm = {{20{instr[31]}} , instr[31:20]}; // I- Instructions + SE
      3'd1: imm = {{20{instr[31]}}, instr[31:25], instr[11:7]}; // S- Instructions  + SE 
      3'd2: imm = {{19{instr[31]}}, instr[7], instr[31], instr[30:25], instr[11:8], 1'b0}; // B-instruction + SE
      3'd3: imm = {instr[31:12], 12'h000}; // U-Instruction + SE
      3'd4: imm = {{11{instr[31]}}, instr[31], instr[19:12], instr[20], instr[30:21], 1'b0}; // J - Instruction + SE           
    endcase   
  end 
  
  
  
  
  
  
endmodule 